<?xml version="1.0"?>
<robot name="robotino" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find pincher_arm_description)/urdf/arm_hardware.xacro"/>
<!-- ***************************** Main Body ***************************** -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.035" rpy="0 0 1.5707"/>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_SplitMain.dae" scale="0.01 0.01 0.01"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.035" rpy="0 0 1.5707"/>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_SplitMain.dae" scale="0.01 0.01 0.01"/>
      </geometry>
    </collision>
  </link>
<!-- ***************************** Wheel 0 - Mesh ***************************** --> 
  <link name="wheel0_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_SplitWheel.dae" scale="0.01 0.01 0.01"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_SplitWheel.dae" scale="0.01 0.01 0.01"/>
      </geometry>
    </collision>
  </link>
<!-- ========== Wheel 0 - Joint ========== --> 
  <joint name="wheel0_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel0_link"/>
    <origin xyz="-0.0001 0.1825 0.059154" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>	
  </joint>
<!-- ***************************** Wheel 1 - Mesh ***************************** --> 
  <link name="wheel1_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_SplitWheel.dae" scale="0.01 0.01 0.01"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_SplitWheel.dae" scale="0.01 0.01 0.01"/>
      </geometry>
    </collision>
  </link>
<!-- ========== Wheel 1 - Joint ========== --> 
  <joint name="wheel1_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel1_link"/>
    <origin xyz="-0.157067 -0.090625 0.059154" rpy="0 0 2.094395102393195"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>	
  </joint>
<!-- ***************************** Wheel 2 - Mesh ***************************** -->  
  <link name="wheel2_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_SplitWheel.dae" scale="0.01 0.01 0.01"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_SplitWheel.dae" scale="0.01 0.01 0.01"/>
      </geometry>
    </collision>
  </link>
<!-- ========== Wheel 2 - Joint ========== --> 
  <joint name="wheel2_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel2_link"/>
    <origin xyz="0.156867 -0.090625 0.059154" rpy="0 0 -2.094395102393195"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>	
  </joint>  
<!-- ***************************** Platform ***************************** -->  
<!-- Un/Comment from here to END to add/remove the platform -->
  <link name="platform_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_Platform.dae" scale="0.009 0.009 0.009"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://robotino_description/model/Robotino3_Platform.dae" scale="0.009 0.009 0.009"/>
      </geometry>
    </collision>
  </link>
<!-- ========== Platform - Joint ========== --> 
  <joint name="platform_joint" type="fixed">
    <parent link="base_link"/>
    <child link="platform_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 0" rpy="0 0 0"/>	
  </joint>
<!-- ***************************** END ***************************** -->  

<!--Hokuyo :P -->
  <link name="hokuyo_laser_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="base_to_hokuyo" type="fixed">
    <parent link="base_link"/>
    <child link="hokuyo_laser_link"/>
    <origin rpy="0 0 0" xyz="0.127 0.0 0.22"/>
  </joint>

<!-- Kinect o stereo camera-->

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.03 0.14 0.0175"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

 <joint name="base_to_kinect" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <!--origin rpy="0 0 0" xyz="0.13 0.0 0.91"/-->
    <origin rpy="0 0 0" xyz="-0.07 0.0 1.22"/>
  </joint>

<!-- ************Arm************ -->

<xacro:macro name="pincher_arm" params="
      color:=Gray
      joints_vlimit:=1.571
      pan_llimit:=-2.617
      pan_ulimit:=2.617
      shoulder_llimit:=-2.09
      shoulder_ulimit:=2.09
      elbow_llimit:=-2.42
      elbow_ulimit:=2.42
      wrist_llimit:=-1.71
      wrist_ulimit:=1.79
      gripper_llimit:=-2.6
      gripper_ulimit:=0.0">

    <link name="arm_base_link"/>
    <joint name="base_to_arm" type="fixed">
	    <parent link="base_link"/>
	    <child link="arm_base_link"/>
	    <origin rpy="0 0 0" xyz="0.15 0.0 0.97"/>
  	</joint>

    <!-- shoulder pan joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_base_link" name="arm_shoulder_pan_servo">
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
    </xacro:dynamixel_AX12_fixed>

    <xacro:bioloid_F3_revolute parent="arm_shoulder_pan_servo_link" name="arm_shoulder_pan" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${pan_llimit}" ulimit="${pan_ulimit}">
      <origin xyz="0 ${AX12_WIDTH/2} 0" rpy="${-pi/2} ${pi/2} ${pi}"/>
    </xacro:bioloid_F3_revolute>

    <!-- shoulder lift joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_shoulder_pan_link" name="arm_shoulder_lift_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${pi} 0"/>
    </xacro:dynamixel_AX12_fixed>

    <xacro:bioloid_F4_revolute parent="arm_shoulder_lift_servo_link" name="arm_shoulder_lift" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${shoulder_llimit}" ulimit="${shoulder_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F4_revolute>

    <xacro:bioloid_F10_fixed parent="arm_shoulder_lift_link" name="arm_shoulder_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F10_fixed parent="arm_shoulder_F10_0_link" name="arm_shoulder_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F10_fixed parent="arm_shoulder_F10_1_link" name="arm_shoulder_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F3_fixed parent="arm_shoulder_F10_2_link" name="arm_shoulder_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${pi} 0"/>
    </xacro:bioloid_F3_fixed>

    <!-- elbow joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_shoulder_F3_0_link" name="arm_elbow_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${pi} 0"/>
    </xacro:dynamixel_AX12_fixed>

    <xacro:bioloid_F4_revolute parent="arm_elbow_flex_servo_link" name="arm_elbow_flex" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${elbow_llimit}" ulimit="${elbow_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F4_revolute>

    <xacro:bioloid_F10_fixed parent="arm_elbow_flex_link" name="arm_elbow_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F10_fixed parent="arm_elbow_F10_0_link" name="arm_elbow_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F10_fixed parent="arm_elbow_F10_1_link" name="arm_elbow_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F3_fixed parent="arm_elbow_F10_2_link" name="arm_elbow_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${pi} 0"/>
    </xacro:bioloid_F3_fixed>

    <!-- wrist joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_elbow_F3_0_link" name="arm_wrist_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${pi} 0"/>
    </xacro:dynamixel_AX12_fixed>

    <xacro:bioloid_F2_revolute parent="arm_wrist_flex_servo_link" name="arm_wrist_flex" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${wrist_llimit}" ulimit="${wrist_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F2_revolute>

    <xacro:bioloid_F3_fixed parent="arm_wrist_flex_link" name="arm_wrist_F3_0" color="${color}">
      <origin xyz="0 0 ${F2_HEIGHT}" rpy="0 ${pi} ${-pi}"/>
    </xacro:bioloid_F3_fixed>
    
    <!-- gripper joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_wrist_F3_0_link" name="gripper_servo" >
      <origin xyz="0 0 ${-AX12_WIDTH/2}" rpy="${pi/2} ${pi} ${pi/2}"/>
    </xacro:dynamixel_AX12_fixed>
    
    <xacro:gripper_finger_base parent="gripper_servo_link" name="gripper_finger_base" color="${color}">
      <origin xyz="0  ${AX12_WIDTH/2} 0" rpy="${pi} 0 ${pi/2}"/>
    </xacro:gripper_finger_base>

    <link name="gripper_active_link"/>
    <joint name="gripper_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit effort="30" velocity="${joints_vlimit}" lower="${gripper_llimit}" upper="${gripper_ulimit}"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_active_link"/>
    </joint>

    <!-- Finger 1 --> 
    <xacro:pincher_finger name="gripper_finger1" color="${color}" >
      <origin xyz="0 0.0115 0" rpy="${pi/2} 0 ${pi/2}"/>
    </xacro:pincher_finger>

    <joint name="gripper_finger1_joint" type="prismatic">
      <origin xyz="0.019 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.01" lower="0.001" upper="0.0158"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_finger1_link"/>
    </joint> 
      
    <!-- Finger 2 -->
    <xacro:pincher_finger name="gripper_finger2" color="${color}" >
      <origin xyz="0 0.0115 0" rpy="${pi/2} 0 ${pi/2}"/>
    </xacro:pincher_finger>

    <joint name="gripper_finger2_joint" type="prismatic">
      <origin xyz="0.019 0 0" rpy="${pi} 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.01" lower="0.001" upper="0.0158"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_finger2_link"/>
      <!-- <mimic joint="gripper_finger1_joint"/> -->
    </joint>

    <!-- fake gripper joint -->
    <link name="gripper_fake_link"/>
    <joint name="gripper_fake_joint" type="revolute">
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_fake_link"/>
      <limit effort="30" velocity="1" lower="-3.14" upper="3.14"/>
      <axis xyz="1 0 0"/>
    </joint>

  </xacro:macro>

</robot>



